# Generated by Django 3.2.7 on 2021-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='avatar',
            field=models.ImageField(default='demo.png', upload_to='images'),
            preserve_default=False,
        ),
    ]
