# Generated by Django 3.2.7 on 2021-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_passenger_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
